name: Deploy KTT app on EC2

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy Angular app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Switch to root user (correct way)
            sudo -i <<EOF
            
            # Update and upgrade system packages
            apt update && apt upgrade -y
            
            # Install dependencies
            apt install -y curl nodejs npm
            
            # Install Angular CLI globally
            npm install -g @angular/cli
            
            # Ensure Git is set up properly
            git config --global --add safe.directory /home/${{ secrets.EC2_USER }}/PrototypeFrontendKTT
            
            # Clone or pull the repository
            if [ -d "PrototypeFrontendKTT" ]; then
              cd PrototypeFrontendKTT
              git pull origin main
            else
              git clone https://${{ secrets.PAT_GITHUB }}@github.com/Shivambembey98/PrototypeFrontendKTT.git
              cd PrototypeFrontendKTT
            fi
            
            # Install Angular dependencies
            npm install
            
            # Start Angular application
            ng serve --host 0.0.0.0 --port 4200

            

            
            
